version: 2.1

orbs:
  heroku: circleci/heroku@1.2.3
  node: circleci/node@4.1.0

workflows:
  build-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - test

jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test    
  deploy:
    executor:
      name: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
